### PR TITLE
Restructure express document parsing code

### PR DESCRIPTION
**Pull request by abunashir**
This commit takes the initial step to restructure existing codebase, and it tries to simplify each of the interfaces and puts them to their dedicated class. This also exposes only a single interface that accepts a Nokogiri document and then instantiates the instances.

This also introduce Nokogiri to parse the XML document, but it keeps the code as similar to the original version so we can easily migrate to this version, but once this is functionality then we should look into each of these classes and do necessary refactoring.

This also imports all of the existing post-processing codes, but these were causing some issues, like slow performance. So, we are disabling this for now, but we've added some @todo comments in each of those inherited codes.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Structure looks like a good start 👍

**Comment by ronaldtse** [comment]
Nokogiri is a runtime dependency, right?

**Comment by abunashir** [comment]
Ah right, changing now 👍

**Comment by ronaldtse** [comment]
@abunashir what's the expected ETA for merging? Thanks!

**Comment by abunashir** [comment]
I'm planning to work over this weekend, but I think we should be done with most of the stuff by the next week.

**Comment by ronaldtse** [comment]
@abunashir we would like to demo some progress by Thursday. Can we merge parts of this first to demonstrate it's working? Thanks!

**Comment by abunashir** [comment]
Hi @ronaldtse, I just finished the parsing part and I'm going to merge this one soon. But, to be perfectly honest, I think we need to add proper testing and everything else before we can actually claim this is working as expected.

I'm not sure if I can work before Thursday, but I will try as much possible, and let you know if there are some progress on this one.

**Comment by ronaldtse** [comment]
@abunashir indeed, we will need to add proper testing, but achievement of existing examples is already good enough, for now.

**Pull request merged**
